services:
  dnsserver:
    build: dnsserver
    hostname: dnsserver
    ports:
      - 10.26.0.7:53:53    #So na rede principal
    volumes:
      - ./dnsserver/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/db.starwars.lan:/etc/bind/db.starwars.lan
      - ./dnsserver/db.192.168.20:/etc/bind/db.192.168.20
    networks:
      rededns:
        ipv4_address: 192.168.20.10
  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 192.168.20.100
    dns: 192.168.20.10
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24
